name: Immortal-Package

on:
  workflow_dispatch:
    inputs:
      wrt_commit:
        description: "Optional specific commit to check out"
        required: false
        default: "bae54687c709f20f0dc18cef033e0bad0159ea23"
      wrt_verbose:
        description: "Enable verbose output"
        required: false
        default: "false"
  schedule:
    - cron: "0 0 * * *"

permissions: write-all

jobs:
  wrt_config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      matrix:
        TARGET: [x86]

    uses: ./.github/workflows/Package-Core.yml
    with:
      WRT_TARGET: ${{matrix.TARGET}}
      WRT_URL: https://github.com/immortalwrt/immortalwrt.git
      WRT_BRANCH: openwrt-24.10
      WRT_COMMIT: ${{ github.event_name == 'schedule' && '78213f3f7acb2a012cc555fdaad85231569c182d' || github.event.inputs.wrt_commit }}
      WRT_VERBOSE: ${{ github.event.inputs.wrt_verbose }}
