name: Immortal

on:
  workflow_dispatch:
    inputs:
      wrt_commit:
        description: "Optional specific commit to check out"
        required: false
        default: ""
      wrt_verbose:
        description: "Enable verbose output"
        required: false
        default: "false"

permissions: write-all

jobs:
  wrt_config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      matrix:
        TARGET: [Rockchip, x86]

    uses: ./.github/workflows/Core.yml
    with:
      WRT_TARGET: ${{matrix.TARGET}}
      WRT_URL: https://github.com/immortalwrt/immortalwrt.git
      WRT_BRANCH: openwrt-24.10
      WRT_IP: 192.168.2.1
      WRT_PASSWORD: admin
      WRT_COMMIT: ${{ github.event.inputs.wrt_commit }}
      WRT_VERBOSE: ${{ github.event.inputs.wrt_verbose }}
