name: Rockchip-Immortal

on:
  workflow_dispatch:
    inputs:
      password:
        description: "Password"
        required: true
        default: ""

permissions: write-all

jobs:
  wrt_config:
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      Target: Rockchip
      RepositoryURL: https://github.com/immortalwrt/immortalwrt.git
      Branch: openwrt-23.05
      IP: 192.168.2.1
      Password: ${{ github.event.inputs.password }}
