name: Rockchip-Immortal

on:
  workflow_dispatch:
    inputs:
      password:
        description: "Password"
        required: true
        default: ""

permissions: write-all

jobs:
  wrt_config:
    uses: ./.github/workflows/Core.yml
    with:
      WRT_TARGET: Rockchip
      WRT_URL: https://github.com/immortalwrt/immortalwrt.git
      WRT_BRANCH: openwrt-23.05
      WRT_IP: 192.168.2.1
      WRT_PASSWORD: ${{ github.event.inputs.password }}
